openapi: 3.0.0
info:
  title: Dashboard Sabrina Costa API
  version: 1.0.0
  description: |
        
            API RESTful completa para o Dashboard Sabrina Costa.
            
            ## Funcionalidades
            
            - 🔐 **Autenticação JWT** - Sistema seguro de login
            - 📊 **Gestão de Métricas** - CRUD completo de métricas do Instagram
            - 📅 **Cronograma de Posts** - Agendamento e gestão de conteúdo
            - 🚨 **Sistema de Alertas** - Notificações automáticas via WhatsApp
            - 🎣 **Ganchos Virais** - Biblioteca de hooks para conteúdo
            - 🔗 **Webhooks** - Integração com sistemas externos
            - ⚙️ **Configurações** - Gestão de parâmetros do sistema
            
            ## Autenticação
            
            Todos os endpoints protegidos exigem um JWT válido no header `Authorization`:
            ```
            Authorization: Bearer <seu-jwt-token>
            ```
            
            ## Rate Limiting
            
            A API implementa rate limiting para garantir estabilidade:
            - **100 requests/minuto** por IP
            - **1000 requests/hora** por usuário autenticado
            
            ## Códigos de Resposta
            
            - `200 OK` - Requisição bem-sucedida
            - `201 Created` - Recurso criado com sucesso
            - `400 Bad Request` - Dados inválidos
            - `401 Unauthorized` - Token ausente/inválido
            - `403 Forbidden` - Acesso negado
            - `404 Not Found` - Recurso não encontrado
            - `429 Too Many Requests` - Rate limit excedido
            - `500 Internal Server Error` - Erro interno
          
servers:
  - url: https://backend-smoky-theta.vercel.app/api
    description: Servidor de Produção
  - url: http://localhost:3000/api
    description: Servidor de Desenvolvimento
tags:
  - name: Autenticação
    description: Endpoints para autenticação e gestão de usuários
  - name: Métricas
    description: Gestão de métricas de desempenho do Instagram
  - name: Cronograma
    description: Agendamento e gestão de posts
  - name: Alertas
    description: Sistema de notificações e alertas
  - name: Ganchos
    description: Biblioteca de ganchos virais e categorias
  - name: Webhooks
    description: Endpoints para integração externa
  - name: Configurações
    description: Gestão de configurações do sistema
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: ID único do usuário
          format: uuid
        email:
          type: string
          description: Email do usuário
          format: email
        name:
          type: string
          description: Nome do usuário
        role:
          type: string
          description: Papel do usuário no sistema
          enum: [user, admin]
        createdAt:
          type: string
          description: Data de criação
          format: date-time
        updatedAt:
          type: string
          description: Data da última atualização
          format: date-time
      required: [id, email, name, role]
    Metric:
      type: object
      properties:
        id:
          type: string
          description: ID único da métrica
          format: uuid
        date:
          type: string
          description: Data da métrica (YYYY-MM-DD)
          format: date
        reach:
          type: integer
          description: Alcance (número de pessoas)
          minimum: 0
        ctr:
          type: number
          description: Taxa de cliques (%)
          format: float
          minimum: 0
          maximum: 100
        cpc:
          type: number
          description: Custo por clique (R$)
          format: float
          minimum: 0
        cpm:
          type: number
          description: Custo por mil impressões (R$)
          format: float
          minimum: 0
        frequency:
          type: number
          description: Frequência de exibição
          format: float
          minimum: 0
        profileVisits:
          type: integer
          description: Visitas ao perfil
          minimum: 0
        newFollowers:
          type: integer
          description: Novos seguidores
          minimum: 0
        cost:
          type: number
          description: Custo total (R$)
          format: float
          minimum: 0
        createdAt:
          type: string
          description: Data de criação
          format: date-time
        updatedAt:
          type: string
          description: Data da última atualização
          format: date-time
      required: [date]
    Post:
      type: object
      properties:
        id:
          type: string
          description: ID único do post
          format: uuid
        date:
          type: string
          description: Data agendada para o post
          format: date
        weekNumber:
          type: integer
          description: Número da semana
          minimum: 1
          maximum: 52
        format:
          type: string
          description: Formato do conteúdo
          enum: [carousel, reel, story, post]
        theme:
          type: string
          description: Tema do post
        hook:
          type: string
          description: Gancho viral do post
        cta:
          type: string
          description: Call-to-action
        status:
          type: string
          description: Status do post
          enum: [planned, published, cancelled]
        createdAt:
          type: string
          description: Data de criação
          format: date-time
        updatedAt:
          type: string
          description: Data da última atualização
          format: date-time
      required: [date, format, theme]
    Alert:
      type: object
      properties:
        id:
          type: string
          description: ID único do alerta
          format: uuid
        type:
          type: string
          description: Tipo do alerta
        message:
          type: string
          description: Mensagem do alerta
        thresholdValue:
          type: number
          description: Valor limite
          format: float
        actualValue:
          type: number
          description: Valor atual
          format: float
        date:
          type: string
          description: Data do alerta
          format: date
        sentAt:
          type: string
          description: Data de envio
          format: date-time
        createdAt:
          type: string
          description: Data de criação
          format: date-time
      required: [type, message, date]
    Hook:
      type: object
      properties:
        id:
          type: string
          description: ID único do gancho
          format: uuid
        title:
          type: string
          description: Título do gancho
        content:
          type: string
          description: Conteúdo do gancho
        category:
          type: string
          description: Categoria do gancho
        usageCount:
          type: integer
          description: Número de usos
          minimum: 0
        createdAt:
          type: string
          description: Data de criação
          format: date-time
        updatedAt:
          type: string
          description: Data da última atualização
          format: date-time
      required: [title, content, category]
    Error:
      type: object
      properties:
        message:
          type: string
          description: Mensagem de erro
        code:
          type: string
          description: Código do erro
        details:
          type: object
          description: Detalhes adicionais do erro
      required: [message]
    Success:
      type: object
      properties:
        message:
          type: string
          description: Mensagem de sucesso
        data:
          type: object
          description: Dados retornados
      required: [message]
paths:
  {}
